server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            # Première route : pour le service produit
            - id: product-service-route
              uri: lb://product-service
              predicates:
                - Path=/api/products/**

            # Seconde route : pour le service commande
            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
